---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - federation.openshift-service-mesh.io
  resources:
  - federatedservices
  - meshfederations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - federation.openshift-service-mesh.io
  resources:
  - federatedservices/finalizers
  - meshfederations/finalizers
  verbs:
  - update
- apiGroups:
  - federation.openshift-service-mesh.io
  resources:
  - federatedservices/status
  - meshfederations/status
  verbs:
  - get
  - patch
  - update
