apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    configSources:
    - address: k8s://
    - address: xds://federation-controller.istio-system.svc.cluster.local:15010
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  values:
    global:
      meshID: west-mesh
      multiCluster:
        clusterName: west-cluster
      network: west-network
    pilot:
      env:
        ENABLE_NATIVE_SIDECARS: "true"
  components:
    ingressGateways:
    - name: istio-eastwestgateway
      label:
        istio: eastwestgateway
        app: istio-eastwestgateway
        topology.istio.io/network: west-network
      enabled: true
      k8s:
        env:
        - name: ISTIO_META_REQUESTED_NETWORK_VIEW
          value: west-network
        service:
          ports:
          - name: discovery
            port: 15080
            targetPort: 15080
          - name: data-plane
            port: 15443
            targetPort: 15443
