apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    configSources:
    - address: k8s://
    - address: xds://federation-controller.istio-system.svc.cluster.local:15010
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  values:
    global:
      meshID: east-mesh
      multiCluster:
        clusterName: east-cluster
      network: east-network
